Repository softeerbootcamp-3nd/softee5-tenten-BE, pull requests merged in 2024-01, with the labels that each got.

#7 feature Entity 생성 및 관계 설정
  src/main/java/softeer/tenten/entity/popup/area/Destination.java
  src/main/java/softeer/tenten/entity/popup/area/Option.java
  src/main/java/softeer/tenten/entity/popup/area/Vote.java
  src/main/java/softeer/tenten/entity/popup/criteria/Brand.java
  src/main/java/softeer/tenten/entity/popup/criteria/Category.java
  src/main/java/softeer/tenten/entity/popup/criteria/PopupTag.java
  src/main/java/softeer/tenten/entity/popup/criteria/Tag.java
  src/main/java/softeer/tenten/entity/popup/event/Event.java
  src/main/java/softeer/tenten/entity/popup/event/UserEvent.java
  src/main/java/softeer/tenten/entity/popup/event/Waiting.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/post/PopupImage.java
  src/main/java/softeer/tenten/entity/popup/review/Review.java
  src/main/java/softeer/tenten/entity/user/User.java
Labels: enhancement

#11 Feat/api 응답 객체 생성 #6
  build/classes/java/main/softeer/tenten/TentenApplication.class
  build/classes/java/main/softeer/tenten/controller/HelloController.class
  build/resources/main/application.yml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/softeer/tenten/global/api/ApiResponse.java
  src/main/java/softeer/tenten/global/api/status/StatusCode.java
  src/main/java/softeer/tenten/global/exception/GeneralException.java
  src/main/java/softeer/tenten/global/handler/GlobalExceptionHandler.java
Labels: enhancement

#13 feature 로그인 API 개발
  src/main/java/softeer/tenten/controller/user/UserController.java
  src/main/java/softeer/tenten/dto/user/UserRequest.java
  src/main/java/softeer/tenten/dto/user/UserResponse.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/global/api/ApiResponse.java
  src/main/java/softeer/tenten/global/api/status/StatusCode.java
  src/main/java/softeer/tenten/mapper/user/UserMapper.java
  src/main/java/softeer/tenten/repository/user/UserRepository.java
  src/main/java/softeer/tenten/service/user/UserService.java
Labels: enhancement

#16 feature 투표 조회 API 개발
  src/main/java/softeer/tenten/controller/popup/area/VoteController.java
  src/main/java/softeer/tenten/dto/popup/area/VoteResponse.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/repository/popup/area/OptionRepository.java
  src/main/java/softeer/tenten/repository/popup/area/VoteRepository.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
Labels: enhancement

#19 feature 팝업 스토어 리스트 조회 api 구현
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/post/PopupImage.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/repository/popup/PopupRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
Labels: enhancement

#20 Feat/팝업 스토어 리스트 조회 기능 개발 #9
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/post/PopupImage.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/repository/popup/PopupRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
Labels: enhancement

#22 feature 투표하기 API 개발
  src/main/java/softeer/tenten/controller/popup/area/VoteController.java
  src/main/java/softeer/tenten/dto/popup/area/VoteRequest.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/repository/popup/area/OptionRepository.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
  src/main/java/softeer/tenten/service/user/UserService.java
Labels: enhancement

#25 feature 팝업 스토어 상세 조회 api 개발
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/controller/popup/area/VoteController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/dto/popup/area/VoteRequest.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/repository/popup/area/OptionRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
  src/main/java/softeer/tenten/service/user/UserService.java
Labels: enhancement

#26 Feat/팝업 스토어 상세 조회 api 개발 #21
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
Labels: enhancement

#28 feature 대기 명단 등록 API 개발
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/area/VoteResponse.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingRequest.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: enhancement

#31 24 feature 대기 명단 등록 api 개발
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/area/VoteResponse.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingRequest.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: enhancement

#33 feature 팝업 스토어 리뷰 조회 api 개발
  src/main/java/softeer/tenten/controller/popup/post/PopupController.java
  src/main/java/softeer/tenten/controller/popup/review/ReviewController.java
  src/main/java/softeer/tenten/dto/popup/post/PopupResponse.java
  src/main/java/softeer/tenten/dto/popup/review/ReviewResponse.java
  src/main/java/softeer/tenten/entity/popup/review/Review.java
  src/main/java/softeer/tenten/mapper/popup/post/PopupMapper.java
  src/main/java/softeer/tenten/mapper/popup/review/ReviewMapper.java
  src/main/java/softeer/tenten/repository/popup/post/PopupRepository.java
  src/main/java/softeer/tenten/repository/popup/review/ReviewRepository.java
  src/main/java/softeer/tenten/service/popup/post/PopupService.java
  src/main/java/softeer/tenten/service/popup/review/ReviewService.java
Labels: enhancement

#35 fix PopupSerivce conflict 해결
  src/main/java/softeer/tenten/controller/popup/post/PopupController.java
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/area/VoteResponse.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingRequest.java
  src/main/java/softeer/tenten/entity/popup/post/Popup.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/mapper/popup/area/VoteMapper.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/area/VoteService.java
  src/main/java/softeer/tenten/service/popup/post/PopupService.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: bug

#36 feature 팝업 스토어 리뷰 조회 api 개발
  src/main/java/softeer/tenten/controller/popup/post/PopupController.java
  src/main/java/softeer/tenten/controller/popup/review/ReviewController.java
  src/main/java/softeer/tenten/dto/popup/post/PopupResponse.java
  src/main/java/softeer/tenten/dto/popup/review/ReviewResponse.java
  src/main/java/softeer/tenten/entity/popup/review/Review.java
  src/main/java/softeer/tenten/mapper/popup/post/PopupMapper.java
  src/main/java/softeer/tenten/mapper/popup/review/ReviewMapper.java
  src/main/java/softeer/tenten/repository/popup/post/PopupRepository.java
  src/main/java/softeer/tenten/repository/popup/review/ReviewRepository.java
  src/main/java/softeer/tenten/service/popup/post/PopupService.java
  src/main/java/softeer/tenten/service/popup/review/ReviewService.java
Labels: bug, enhancement

#38 feature 대기 명단 조회 API 개발
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingResponse.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: enhancement

#39 feat/대기 명단 조회 api 개발 #32
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingResponse.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: enhancement

#40 feature 팝업 스토어 이벤트 전체 조회 api 개발
  src/main/java/softeer/tenten/controller/popup/event/EventController.java
  src/main/java/softeer/tenten/controller/popup/waiting/WaitingController.java
  src/main/java/softeer/tenten/dto/popup/event/EventResponse.java
  src/main/java/softeer/tenten/dto/popup/waiting/WaitingResponse.java
  src/main/java/softeer/tenten/entity/popup/event/Event.java
  src/main/java/softeer/tenten/entity/popup/waiting/Waiting.java
  src/main/java/softeer/tenten/mapper/popup/event/EventMapper.java
  src/main/java/softeer/tenten/mapper/popup/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/repository/popup/event/EventRepository.java
  src/main/java/softeer/tenten/repository/popup/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/popup/event/EventService.java
  src/main/java/softeer/tenten/service/popup/waiting/WaitingService.java
Labels: enhancement

#41 Feat/팝업 스토어 이벤트 조회 api 개발 #37
  src/main/java/softeer/tenten/controller/popup/event/EventController.java
  src/main/java/softeer/tenten/dto/popup/event/EventResponse.java
  src/main/java/softeer/tenten/entity/popup/event/Event.java
  src/main/java/softeer/tenten/mapper/popup/event/EventMapper.java
  src/main/java/softeer/tenten/repository/popup/event/EventRepository.java
  src/main/java/softeer/tenten/service/popup/event/EventService.java
Labels: enhancement

#46 feature 팝업 스토어 이벤트 단건 조회 api 개발
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/service/event/EventService.java
Labels: enhancement

#47 Feat/팝업 스토어 이벤트 상세 조회 #45
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/service/event/EventService.java
Labels: enhancement

#49 feature 이벤트 참가 기능 api 개발
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/controller/event/UserEventController.java
  src/main/java/softeer/tenten/dto/event/EventRequest.java
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/repository/event/UserEventRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
Labels: bug, enhancement

#50 Feat/이벤트 참가 기능 api 개발 #48
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/controller/event/UserEventController.java
  src/main/java/softeer/tenten/dto/event/EventRequest.java
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/repository/event/UserEventRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
Labels: enhancement, refactoring

#52 refactoring Exception handling
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/review/ReviewService.java
Labels: enhancement, refactoring

#53 Refact/exception 반환 처리 #51
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/review/ReviewService.java
Labels: enhancement, refactoring

#54 refactoring git ignore 파일 설정
  .DS_Store
  .gitignore
  .gradle/8.5/checksums/checksums.lock
  .gradle/8.5/checksums/md5-checksums.bin
  .gradle/8.5/checksums/sha1-checksums.bin
  .gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.5/dependencies-accessors/gc.properties
  .gradle/8.5/executionHistory/executionHistory.bin
  .gradle/8.5/executionHistory/executionHistory.lock
  .gradle/8.5/fileChanges/last-build.bin
  .gradle/8.5/fileHashes/fileHashes.bin
  .gradle/8.5/fileHashes/fileHashes.lock
  .gradle/8.5/fileHashes/resourceHashesCache.bin
  .gradle/8.5/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/tenten.main.iml
  .idea/vcs.xml
Labels: refactoring

#55 fix Event <-> Popup 관계 설정
  src/main/java/softeer/tenten/entity/event/Event.java
  src/main/java/softeer/tenten/entity/popup/Popup.java
  src/main/java/softeer/tenten/repository/event/EventRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
Labels: bug

#57 feature Aws S3 Configuration 설정
  build.gradle
  src/main/java/softeer/tenten/config/S3/S3Config.java
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/repository/event/EventRepository.java
  src/main/java/softeer/tenten/service/S3/AwsS3Service.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/resources/application.yml
Labels: enhancement, refactoring

#58 Feat/aws s3 configuration #56
  build.gradle
  src/main/java/softeer/tenten/config/S3/S3Config.java
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/repository/event/EventRepository.java
  src/main/java/softeer/tenten/service/S3/AwsS3Service.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/resources/application.yml
Labels: enhancement, refactoring

#59 feature 팝업 스토어 전체 조회시에 거리순 정렬 기능 구현
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/review/ReviewService.java
Labels: enhancement

#60 fix Entity 관계 설정 변경 및 필드 수정
  src/main/java/softeer/tenten/entity/area/Destination.java
  src/main/java/softeer/tenten/entity/area/Option.java
  src/main/java/softeer/tenten/entity/criteria/Brand.java
  src/main/java/softeer/tenten/entity/criteria/Category.java
  src/main/java/softeer/tenten/entity/criteria/PopupTag.java
  src/main/java/softeer/tenten/entity/criteria/Tag.java
  src/main/java/softeer/tenten/entity/event/Event.java
  src/main/java/softeer/tenten/entity/event/UserEvent.java
  src/main/java/softeer/tenten/entity/popup/Popup.java
  src/main/java/softeer/tenten/entity/popup/PopupImage.java
  src/main/java/softeer/tenten/entity/review/Review.java
  src/main/java/softeer/tenten/entity/user/User.java
  src/main/java/softeer/tenten/entity/vote/Vote.java
  src/main/java/softeer/tenten/entity/waiting/Waiting.java
  src/main/java/softeer/tenten/mapper/review/ReviewMapper.java
  src/main/resources/application.yml
Labels: bug, refactoring

#61 fix 팝업 스토어 전체 조회 정렬 기능 수정
  .idea/modules/tenten.main.iml
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/controller/popup/PopupController.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/entity/area/Destination.java
  src/main/java/softeer/tenten/entity/popup/Popup.java
  src/main/java/softeer/tenten/entity/review/Review.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/review/ReviewMapper.java
  src/main/java/softeer/tenten/repository/event/EventRepository.java
  src/main/java/softeer/tenten/repository/popup/PopupRepository.java
  src/main/java/softeer/tenten/repository/review/ReviewRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
  src/main/java/softeer/tenten/service/review/ReviewService.java
  src/main/resources/application.yml
Labels: bug, refactoring

#62 fix Request Entity 필드 타입 수정
  src/main/java/softeer/tenten/controller/event/UserEventController.java
  src/main/java/softeer/tenten/dto/event/EventRequest.java
  src/main/java/softeer/tenten/dto/waiting/WaitingRequest.java
  src/main/java/softeer/tenten/mapper/vote/VoteMapper.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/user/UserService.java
  src/main/java/softeer/tenten/service/vote/VoteService.java
Labels: bug

#66 fix, refactor 중복 투표 버그 해걸, repository에 _ 제거
  src/main/java/softeer/tenten/repository/area/OptionRepository.java
  src/main/java/softeer/tenten/repository/vote/VoteRepository.java
  src/main/java/softeer/tenten/repository/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/vote/VoteService.java
Labels: bug, refactoring

#68 chore Dockerfile 생성
  Dockerfile
  build.gradle
Labels: deployment

#70 chore: ignore 파일 설정
  .gitignore
  .idea/dataSources.xml
  .idea/modules/tenten.main.iml
  Dockerfile
  HELP.md
  README.md
  src/main/java/softeer/tenten/config/S3/S3Config.java
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/service/S3/AwsS3Service.java
  src/main/java/softeer/tenten/service/waiting/WaitingService.java
  src/main/resources/application.yml
Labels: refactoring

#71 fix waiting 대기 번호 및 내 앞 대기 인원 조회 안되는 현상 수정
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/service/waiting/WaitingService.java
Labels: bug

#72 Fix/waiting 대기 번호 내 앞 대기 인원 안나오는 현상 수정 #69
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/waiting/WaitingMapper.java
  src/main/java/softeer/tenten/service/waiting/WaitingService.java
Labels: bug

#74 fix Api 조회시 누락된 데이터 보내도록 수정
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/dto/review/ReviewResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/review/ReviewMapper.java
  src/main/java/softeer/tenten/repository/popup/PopupImageRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
Labels: bug

#75 Fix/api 조회시 누락된 데이터 보내도록 수정 73#
  src/main/java/softeer/tenten/dto/event/EventResponse.java
  src/main/java/softeer/tenten/dto/popup/PopupResponse.java
  src/main/java/softeer/tenten/dto/review/ReviewResponse.java
  src/main/java/softeer/tenten/mapper/event/EventMapper.java
  src/main/java/softeer/tenten/mapper/popup/PopupMapper.java
  src/main/java/softeer/tenten/mapper/review/ReviewMapper.java
  src/main/java/softeer/tenten/repository/popup/PopupImageRepository.java
  src/main/java/softeer/tenten/service/popup/PopupService.java
Labels: bug

#76 fix waiting 삭제 후 재등록 되도록 수정
  src/main/java/softeer/tenten/repository/waiting/WaitingRepository.java
Labels: bug

#79 fix 이벤트 참여, 대기 명단 등록 수정
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/controller/event/UserEventController.java
  src/main/java/softeer/tenten/dto/event/EventRequest.java
  src/main/java/softeer/tenten/repository/event/UserEventRepository.java
  src/main/java/softeer/tenten/repository/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/waiting/WaitingService.java
Labels: bug

#80 Fix/이벤트 참여 대기 명단 등록 및 조회 수정 #78
  src/main/java/softeer/tenten/controller/event/EventController.java
  src/main/java/softeer/tenten/controller/event/UserEventController.java
  src/main/java/softeer/tenten/dto/event/EventRequest.java
  src/main/java/softeer/tenten/repository/event/UserEventRepository.java
  src/main/java/softeer/tenten/repository/waiting/WaitingRepository.java
  src/main/java/softeer/tenten/service/event/EventService.java
  src/main/java/softeer/tenten/service/event/UserEventService.java
  src/main/java/softeer/tenten/service/waiting/WaitingService.java
Labels: bug

#82 fix: 투표 결과 조회 시 자신이 투표한 옵션도 응답 데이터로 제공하도록 수정
  src/main/java/softeer/tenten/controller/vote/VoteController.java
  src/main/java/softeer/tenten/dto/vote/VoteResponse.java
  src/main/java/softeer/tenten/mapper/vote/VoteMapper.java
  src/main/java/softeer/tenten/service/vote/VoteService.java
Labels: bug

#83 Fix/투표 결과 조회 시 자신이 투표한 옵션을 응답에 추가 81
  src/main/java/softeer/tenten/controller/vote/VoteController.java
  src/main/java/softeer/tenten/dto/vote/VoteResponse.java
  src/main/java/softeer/tenten/mapper/vote/VoteMapper.java
  src/main/java/softeer/tenten/service/vote/VoteService.java
Labels: bug

#84 docs README 업데이트
  README.md
Labels: documentation
